export const countries = [
  {country: 'Albania', code: 'AL', prefix: '+355'},
  {country: 'Algeria', code: 'DZ', prefix: '+213'},
  {country: 'Andorra', code: 'AD', prefix: '+376'},
  {country: 'Angola', code: 'AO', prefix: '+244'},
  {country: 'Argentina', code: 'AR', prefix: '+54'},
  {country: 'Armenia', code: 'AM', prefix: '+374'},
  {country: 'Australia', code: 'AU', prefix: '+61'},
  {country: 'Austria', code: 'AT', prefix: '+43'},
  {country: 'Azerbaijan', code: 'AZ', prefix: '+994'},
  {country: 'Bahrain', code: 'BH', prefix: '+973'},
  {country: 'Bangladesh', code: 'BD', prefix: '+880'},
  {country: 'Belarus', code: 'BY', prefix: '+375'},
  {country: 'Belgium', code: 'BE', prefix: '+32'},
  {country: 'Belize', code: 'BZ', prefix: '+501'},
  {country: 'Benin', code: 'BJ', prefix: '+229'},
  {country: 'Bhutan', code: 'BT', prefix: '+975'},
  {country: 'Bolivia', code: 'BO', prefix: '+591'},
  {country: 'Bosnia and Herzegovina', code: 'BA', prefix: '+387'},
  {country: 'Botswana', code: 'BW', prefix: '+267'},
  {country: 'Brazil', code: 'BR', prefix: '+55'},
  {country: 'Brunei', code: 'BN', prefix: '+673'},
  {country: 'Bulgaria', code: 'BG', prefix: '+359'},
  {country: 'Burkina Faso', code: 'BF', prefix: '+226'},
  {country: 'Burundi', code: 'BI', prefix: '+257'},
  {country: 'Cambodia', code: 'KH', prefix: '+855'},
  {country: 'Cameroon', code: 'CM', prefix: '+237'},
  {country: 'Canada', code: 'CA', prefix: '+1'},
  {country: 'Cape Verde', code: 'CV', prefix: '+238'},
  {country: 'Central African Republic', code: 'CF', prefix: '+236'},
  {country: 'Chad', code: 'TD', prefix: '+235'},
  {country: 'Chile', code: 'CL', prefix: '+56'},
  {country: 'China', code: 'CN', prefix: '+86'},
  {country: 'Colombia', code: 'CO', prefix: '+57'},
  {country: 'Comoros', code: 'KM', prefix: '+269'},
  {country: 'Congo (Democratic Republic)', code: 'CD', prefix: '+243'},
  {country: 'Congo (Republic)', code: 'CG', prefix: '+242'},
  {country: 'Costa Rica', code: 'CR', prefix: '+506'},
  {country: 'Croatia', code: 'HR', prefix: '+385'},
  {country: 'Cuba', code: 'CU', prefix: '+53'},
  {country: 'Cyprus', code: 'CY', prefix: '+357'},
  {country: 'Czech Republic', code: 'CZ', prefix: '+420'},
  {country: 'Denmark', code: 'DK', prefix: '+45'},
  {country: 'Djibouti', code: 'DJ', prefix: '+253'},
  {country: 'Dominica', code: 'DM', prefix: '+1-767'},
  {country: 'Dominican Republic', code: 'DO', prefix: '+1-809, +1-829, +1-849'},
  {country: 'Ecuador', code: 'EC', prefix: '+593'},
  {country: 'Egypt', code: 'EG', prefix: '+20'},
  {country: 'El Salvador', code: 'SV', prefix: '+503'},
  {country: 'Equatorial Guinea', code: 'GQ', prefix: '+240'},
  {country: 'Eritrea', code: 'ER', prefix: '+291'},
  {country: 'Estonia', code: 'EE', prefix: '+372'},
  {country: 'Eswatini', code: 'SZ', prefix: '+268'},
  {country: 'Ethiopia', code: 'ET', prefix: '+251'},
  {country: 'Fiji', code: 'FJ', prefix: '+679'},
  {country: 'Finland', code: 'FI', prefix: '+358'},
  {country: 'France', code: 'FR', prefix: '+33'},
  {country: 'Gabon', code: 'GA', prefix: '+241'},
  {country: 'Gambia', code: 'GM', prefix: '+220'},
  {country: 'Georgia', code: 'GE', prefix: '+995'},
  {country: 'Germany', code: 'DE', prefix: '+49'},
  {country: 'Ghana', code: 'GH', prefix: '+233'},
  {country: 'Greece', code: 'GR', prefix: '+30'},
  {country: 'Grenada', code: 'GD', prefix: '+1-473'},
  {country: 'Guatemala', code: 'GT', prefix: '+502'},
  {country: 'Guinea', code: 'GN', prefix: '+224'},
  {country: 'Guinea-Bissau', code: 'GW', prefix: '+245'},
  {country: 'Guyana', code: 'GY', prefix: '+592'},
  {country: 'Haiti', code: 'HT', prefix: '+509'},
  {country: 'Honduras', code: 'HN', prefix: '+504'},
  {country: 'Hungary', code: 'HU', prefix: '+36'},
  {country: 'Iceland', code: 'IS', prefix: '+354'},
  {country: 'India', code: 'IN', prefix: '+91'},
  {country: 'Indonesia', code: 'ID', prefix: '+62'},
  {country: 'Iran', code: 'IR', prefix: '+98'},
  {country: 'Iraq', code: 'IQ', prefix: '+964'},
  {country: 'Ireland', code: 'IE', prefix: '+353'},
  {country: 'Israel', code: 'IL', prefix: '+972'},
  {country: 'Italy', code: 'IT', prefix: '+39'},
  {country: 'Ivory Coast', code: 'CI', prefix: '+225'},
  {country: 'Jamaica', code: 'JM', prefix: '+1-876'},
  {country: 'Japan', code: 'JP', prefix: '+81'},
  {country: 'Jordan', code: 'JO', prefix: '+962'},
  {country: 'Kazakhstan', code: 'KZ', prefix: '+7'},
  {country: 'Kenya', code: 'KE', prefix: '+254'},
  {country: 'Kiribati', code: 'KI', prefix: '+686'},
  {country: 'Kuwait', code: 'KW', prefix: '+965'},
  {country: 'Kyrgyzstan', code: 'KG', prefix: '+996'},
  {country: 'Laos', code: 'LA', prefix: '+856'},
  {country: 'Latvia', code: 'LV', prefix: '+371'},
  {country: 'Lebanon', code: 'LB', prefix: '+961'},
  {country: 'Lesotho', code: 'LS', prefix: '+266'},
  {country: 'Liberia', code: 'LR', prefix: '+231'},
  {country: 'Libya', code: 'LY', prefix: '+218'},
  {country: 'Liechtenstein', code: 'LI', prefix: '+423'},
  {country: 'Lithuania', code: 'LT', prefix: '+370'},
  {country: 'Luxembourg', code: 'LU', prefix: '+352'},
  {country: 'Madagascar', code: 'MG', prefix: '+261'},
  {country: 'Malawi', code: 'MW', prefix: '+265'},
  {country: 'Malaysia', code: 'MY', prefix: '+60'},
  {country: 'Maldives', code: 'MV', prefix: '+960'},
  {country: 'Mali', code: 'ML', prefix: '+223'},
  {country: 'Malta', code: 'MT', prefix: '+356'},
  {country: 'Marshall Islands', code: 'MH', prefix: '+692'},
  {country: 'Mauritania', code: 'MR', prefix: '+222'},
  {country: 'Mauritius', code: 'MU', prefix: '+230'},
  {country: 'Mexico', code: 'MX', prefix: '+52'},
  {country: 'Micronesia', code: 'FM', prefix: '+691'},
  {country: 'Moldova', code: 'MD', prefix: '+373'},
  {country: 'Monaco', code: 'MC', prefix: '+377'},
  {country: 'Mongolia', code: 'MN', prefix: '+976'},
  {country: 'Montenegro', code: 'ME', prefix: '+382'},
  {country: 'Morocco', code: 'MA', prefix: '+212'},
  {country: 'Mozambique', code: 'MZ', prefix: '+258'},
  {country: 'Myanmar', code: 'MM', prefix: '+95'},
  {country: 'Namibia', code: 'NA', prefix: '+264'},
  {country: 'Nauru', code: 'NR', prefix: '+674'},
  {country: 'Nepal', code: 'NP', prefix: '+977'},
  {country: 'Netherlands', code: 'NL', prefix: '+31'},
  {country: 'New Zealand', code: 'NZ', prefix: '+64'},
  {country: 'Nicaragua', code: 'NI', prefix: '+505'},
  {country: 'Niger', code: 'NE', prefix: '+227'},
  {country: 'Nigeria', code: 'NG', prefix: '+234'},
  {country: 'North Korea', code: 'KP', prefix: '+850'},
  {country: 'North Macedonia', code: 'MK', prefix: '+389'},
  {country: 'Norway', code: 'NO', prefix: '+47'},
  {country: 'Oman', code: 'OM', prefix: '+968'},
  {country: 'Pakistan', code: 'PK', prefix: '+92'},
  {country: 'Palau', code: 'PW', prefix: '+680'},
  {country: 'Palestine', code: 'PS', prefix: '+970'},
  {country: 'Panama', code: 'PA', prefix: '+507'},
  {country: 'Papua New Guinea', code: 'PG', prefix: '+675'},
  {country: 'Paraguay', code: 'PY', prefix: '+595'},
  {country: 'Peru', code: 'PE', prefix: '+51'},
  {country: 'Philippines', code: 'PH', prefix: '+63'},
  {country: 'Poland', code: 'PL', prefix: '+48'},
  {country: 'Portugal', code: 'PT', prefix: '+351'},
  {country: 'Qatar', code: 'QA', prefix: '+974'},
  {country: 'Romania', code: 'RO', prefix: '+40'},
  {country: 'Russia', code: 'RU', prefix: '+7'},
  {country: 'Rwanda', code: 'RW', prefix: '+250'},
  {country: 'Saint Kitts and Nevis', code: 'KN', prefix: '+1-869'},
  {country: 'Saint Lucia', code: 'LC', prefix: '+1-758'},
  {country: 'Saint Vincent and the Grenadines', code: 'VC', prefix: '+1-784'},
  {country: 'Samoa', code: 'WS', prefix: '+685'},
  {country: 'San Marino', code: 'SM', prefix: '+378'},
  {country: 'Sao Tome and Principe', code: 'ST', prefix: '+239'},
  {country: 'Saudi Arabia', code: 'SA', prefix: '+966'},
  {country: 'Senegal', code: 'SN', prefix: '+221'},
  {country: 'Serbia', code: 'RS', prefix: '+381'},
  {country: 'Seychelles', code: 'SC', prefix: '+248'},
  {country: 'Sierra Leone', code: 'SL', prefix: '+232'},
  {country: 'Singapore', code: 'SG', prefix: '+65'},
  {country: 'Slovakia', code: 'SK', prefix: '+421'},
  {country: 'Slovenia', code: 'SI', prefix: '+386'},
  {country: 'Solomon Islands', code: 'SB', prefix: '+677'},
  {country: 'Somalia', code: 'SO', prefix: '+252'},
  {country: 'South Africa', code: 'ZA', prefix: '+27'},
  {country: 'South Korea', code: 'KR', prefix: '+82'},
  {country: 'South Sudan', code: 'SS', prefix: '+211'},
  {country: 'Spain', code: 'ES', prefix: '+34'},
  {country: 'Sri Lanka', code: 'LK', prefix: '+94'},
  {country: 'Sudan', code: 'SD', prefix: '+249'},
  {country: 'Suriname', code: 'SR', prefix: '+597'},
  {country: 'Sweden', code: 'SE', prefix: '+46'},
  {country: 'Switzerland', code: 'CH', prefix: '+41'},
  {country: 'Syria', code: 'SY', prefix: '+963'},
  {country: 'Taiwan', code: 'TW', prefix: '+886'},
  {country: 'Tajikistan', code: 'TJ', prefix: '+992'},
  {country: 'Tanzania', code: 'TZ', prefix: '+255'},
  {country: 'Thailand', code: 'TH', prefix: '+66'},
  {country: 'Togo', code: 'TG', prefix: '+228'},
  {country: 'Tonga', code: 'TO', prefix: '+676'},
  {country: 'Trinidad and Tobago', code: 'TT', prefix: '+1-868'},
  {country: 'Tunisia', code: 'TN', prefix: '+216'},
  {country: 'Turkey', code: 'TR', prefix: '+90'},
  {country: 'Turkmenistan', code: 'TM', prefix: '+993'},
  {country: 'Tuvalu', code: 'TV', prefix: '+688'},
  {country: 'Uganda', code: 'UG', prefix: '+256'},
  {country: 'Ukraine', code: 'UA', prefix: '+380'},
  {country: 'United Arab Emirates', code: 'AE', prefix: '+971'},
  {country: 'United Kingdom', code: 'GB', prefix: '+44'},
  {country: 'United States', code: 'US', prefix: '+1'},
  {country: 'Uruguay', code: 'UY', prefix: '+598'},
  {country: 'Uzbekistan', code: 'UZ', prefix: '+998'},
  {country: 'Vanuatu', code: 'VU', prefix: '+678'},
  {country: 'Vatican City', code: 'VA', prefix: '+379'},
  {country: 'Venezuela', code: 'VE', prefix: '+58'},
  {country: 'Vietnam', code: 'VN', prefix: '+84'},
  {country: 'Yemen', code: 'YE', prefix: '+967'},
  {country: 'Zambia', code: 'ZM', prefix: '+260'},
  {country: 'Zimbabwe', code: 'ZW', prefix: '+263'},
];
